<div class="loadingio-spinner-dual-ring-30iqxaecl3i"><div class="ldio-2h4jvlywlic">
<div></div><div><div></div></div>
</div></div>
<style type="text/css">
@keyframes ldio-2h4jvlywlic {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
.ldio-2h4jvlywlic div { box-sizing: border-box!important }
.ldio-2h4jvlywlic > div {
  position: absolute;
  width: 72px;
  height: 72px;
  top: 14px;
  left: 14px;
  border-radius: 50%;
  border: 8px solid #000;
  border-color: #71b2fe transparent #71b2fe transparent;
  animation: ldio-2h4jvlywlic 1s linear infinite;
}
.ldio-2h4jvlywlic > div:nth-child(2) { border-color: transparent }
.ldio-2h4jvlywlic > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-2h4jvlywlic > div:nth-child(2) div:before, .ldio-2h4jvlywlic > div:nth-child(2) div:after { 
  content: "";
  display: block;
  position: absolute;
  width: 8px;
  height: 8px;
  top: -8px;
  left: 24px;
  background: #71b2fe;
  border-radius: 50%;
  box-shadow: 0 64px 0 0 #71b2fe;
}
.ldio-2h4jvlywlic > div:nth-child(2) div:after { 
  left: -8px;
  top: 24px;
  box-shadow: 64px 0 0 0 #71b2fe;
}
.loadingio-spinner-dual-ring-30iqxaecl3i {
  width: 64px;
  height: 64px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-2h4jvlywlic {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.64);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-2h4jvlywlic div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>